name: ci

on:
  push:

jobs:
  docker:
    runs-on: windows-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vitorlassen
          password: dckr_pat_UvRQB8J-riyK6LdobxR_kZ2ua7g
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vitorlassen/timer-actions:latest
